# Generated by Django 6.1.1 on 2026-09-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('completado', 'Completado'), ('fallida', 'Fallida')], default='pendiente', max_length=20),
        ),
    ]
