# Generated by Django 6.1.1 on 2026-09-20 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_estado_completado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion_stellar', models.CharField(max_length=56)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recolector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='core.operador')),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='core.recolector')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=7, max_digits=12)),
                ('cantidad_baldes', models.PositiveIntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='puntos/')),
                ('gemini_cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('gemini_consistente', models.BooleanField(blank=True, null=True)),
                ('gemini_respuesta', models.TextField(blank=True)),
                ('gemini_error', models.TextField(blank=True)),
                ('token_confirmacion', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('confirmacion', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_revision', 'En revisión'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('motivo_no_pago', models.TextField(blank=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='core.ruta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
