# Generated by Django 6.1.1 on 2026-09-20 16:50

import django.db.models.deletion
from django.db import migrations, models


def wipe_payments(apps, schema_editor):
    Payment = apps.get_model("core", "Payment")
    Payment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operador_recolector_ruta_punto'),
    ]

    operations = [
        migrations.RunPython(wipe_payments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='payment',
            name='task',
        ),
        migrations.AddField(
            model_name='payment',
            name='punto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.punto'),
        ),
    ]
