# Generated by Django 6.1.1 on 2026-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_punto_catalogo_ruta_visita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punto',
            options={'ordering': ['nombre'], 'verbose_name': 'punto', 'verbose_name_plural': 'puntos (catálogo)'},
        ),
        migrations.AlterField(
            model_name='ruta',
            name='monto',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
    ]
