# Generated by Django 6.1.1 on 2026-09-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_punto_promedio_y_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='operador',
            name='nombre',
        ),
    ]
