# Generated by Django 6.1.1 on 2026-09-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quitar_nombre_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_revision', 'En revisión'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
